# Perfil ativo (usando dados de teste do TestConfig)
spring.profiles.active=test

# Configurações do H2 Console (banco de dados em memória)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=